### ISSUE TITLE
As a user, I want to clearly see in the UI if my transaction is pending. 

### ISSUE THREAD

**Issue by k-misztal** [TheMindhouse/cryptocanvas#11]
As a user, I want to clearly see in the website's UI if my transaction is pending. It would be good to add some more loaders, like in the setting pixel transaction. That includes:
- [x] Add a loader to my account balance when there is pending withdrawal transaction. 
- [x] Add a loader when to canvas details window when there is a _get reward_ transaction pending. 
- [x] Add a loader to initial bidding view, when there is _post a bid_ transaction pending. 

_Note: if that issue is time-consuming let's move it out of the **Release 1.0** milestone._

**Comment by krisu-pl** [comment]
It actually looks better than expected, and I created one super reusable component, so I added such info to every transaction :)
