### ISSUE TITLE
Investigate events emitted when selling canvas

### ISSUE THREAD

**Issue by krisu-pl** [TheMindhouse/cryptocanvas#16]
There seems to be something wrong with emitted events. 
When accepting Sell offer, `from` and `to` addresses are the same. 
When accepting Buy offer by the owner, the amount is 0 and `to` address is 0x0
![image](https://user-images.githubusercontent.com/7289999/39396171-3bc2ebbe-4ae1-11e8-87a0-2c6a1b0678ec.png)

**Comment by krisu-pl** [comment]
@k-misztal it may be caused because Solidity uses pointers instead of copying variables... check this out. If that's the case 

![image](https://user-images.githubusercontent.com/7289999/39396256-b4e45fa4-4ae2-11e8-869c-69b8f1c3aeea.png)

**Comment by krisu-pl** [comment]
Same error as above, but in function `acceptSellOffer`.

First, you make the sender the owner of the canvas (correct).
```
        canvas.owner = msg.sender;
        cancelSellOffer(_canvasId);

        emit CanvasSold(_canvasId, msg.value, sellOffer.seller, msg.sender);
```
 But then you execute `cancelSellOffer` 
```
 require(canvas.owner == msg.sender);
 canvasForSale[_canvasId] = SellOffer(false, msg.sender, 0, 0x0);
```
where you change the sell offer seller to `msg.sender`, which is actually the buyer in this case

**Comment by krisu-pl** [comment]
FYI moving emitting events above the critical lines solves the problem, but I'd still take a deeper look into the whole contract and other events

**Comment by krisu-pl** [comment]
One more thing, event `CanvasNoLongerForSale` is our only indicator of "Sell Offer Cancelled". It shouldn't be triggered when accepting sell offer as we would have 2 events in the history (Canvas Sold & Sell Offer Cancelled). I think `cancelSellOffer` function should be split into two, so you can reset the sell offer but not emit the event.

**Comment by k-misztal** [comment]
Fixed.
