### ISSUE TITLE
Fix a Metamask bug

### ISSUE THREAD

**Issue by k-misztal** [TheMindhouse/cryptocanvas#2]
When Metamask account is changed, transactions are still sent from the old one.

**Suggestion**: what if we reload the page each time MetaMask changes account? It should fix most of the problems of that kind.

**Comment by krisu-pl** [comment]
I couldn't fix it, so, for now, we're reloading the page after changing account

**Comment by krisu-pl** [comment]
I actually found out a way to make it work, so now it works without reloading! :) 🚀
