### ISSUE TITLE
As a user I want to see if my transaction is completed or failed. 

### ISSUE THREAD

**Issue by k-misztal** [TheMindhouse/cryptocanvas#3]
As a user, each time I send a transaction to the Ethereum blockchain, I want to be informed if it completed or failed. 

_Edit: I created that issue because it was in your ToDoist, but actually it looks like it's done. I think the box in the bottom right corner is just what we need. Please close it if you agree with that._

**Comment by krisu-pl** [comment]
This task was an enhancement to show a notification once a transaction is completed/failed.

**Comment by k-misztal** [comment]
Right now it shows transaction with 3 possible statues: `pending`, `completed`, `failed`. So it's even better. What do you want to change here?

**Comment by krisu-pl** [comment]
Widget at the bottom is quite small. It's easy to not notice some changes, so I want to show a notification in upper right corner when status of a transaction changes

**Comment by krisu-pl** [comment]
Done with 6963e49cdedf72fe0c381fbcdbf35f437d5ac018
