### ISSUE TITLE
As a user, I want to see canvas' transaction history

### ISSUE THREAD

**Issue by k-misztal** [TheMindhouse/cryptocanvas#4]
As a user, I want to see all canvas' transaction history. History should be placed in the details page of canvas and include: 
- [x] History of initial bidding: who won the initial bidding, and all bids placed for canvas. 
- [x] History of all finalized transactions, so when the canvas has changed the owner. Technically, it means whenever function `acceptBuyOffer` or `acceptSellOffer` is called. 
- [x] _History of all made sell/buy offers. To be discussed if we want that_.

**Comment by krisu-pl** [comment]
Almost done but blocked by #16 and #17

**Comment by krisu-pl** [comment]
Finished, showing
* Bids
* Highest Bid
* Buy Offer
* Sell Offer
* Buy Offer Cancelled
* Sell Offer Cancelled
* Canvas Sold (Buy/Sell Offer Accepted)
