### ISSUE TITLE
Improve the Transaction List modal

### ISSUE THREAD

**Issue by k-misztal** [TheMindhouse/cryptocanvas#6]
Transaction List modal looks a bit messy for me. What I'd do is: 
- [x] Redesign it a bit. Make all the text justified, or something. We can talk about it. Nothing fancy nor time-consuming. I don't want you to spend too much time on this. 
- [ ] For completed and failed transaction it'd be awesome to have information **how much gas has been used**. I think that this is a very important point.

**Comment by krisu-pl** [comment]
Modal is redesigned. You can see gas used on etherscan page. I don't think that's something an average user is looking for. It can certainly be added as a bonus feature later
![image](https://user-images.githubusercontent.com/7289999/39365421-02d703b6-4a29-11e8-92c7-5eba43096bac.png)
