### ISSUE TITLE
As a user I want to see more scaled gas limit. 

### ISSUE THREAD

**Issue by k-misztal** [TheMindhouse/cryptocanvas#9]
As a user, I want to see a well-scaled gas limit. Right now it's as high as **3.000.000** which suggests our transactions are way more expensive than they really are. According to my gas calculator, it should be enough to set a limit to *150.000*. Below I paste functions' gas cost. 

Gas costs for a canvas of 4096 pixels:

Function | Gas cost 
--- | ---: 
createCanvas() | 91852
setPixel() _(new one)_ | 96671
setPixel() _(update)_ | 51946
setPixel() _(last one)_ | 63765
makeBid() _(first one)_ | 114453
makeBid() _(outbidding someone)_ | 78442
addRewardToPendingWithdrawals() | 63942
addCommissionToPendingWithdrawals() | 57424
setMinimumBidAmount() | 27502
offerCanvasForSaleToAddress() | 95385
offerCanvasForSale() | 33153
cancelSellOffer() | 32752
acceptSellOffer() | 87970
acceptSellOffer() _(when having buy offer posted)_ | 66278
makeBuyOffer() | 73882
makeBuyOffer() _(outbidding someone)_ | 51805
cancelBuyOffer() | 35522
acceptBuyOffer() | 57065
withdraw() | 22677

**Comment by krisu-pl** [comment]
Created 3 gas limits

Function | Gas cost 
--- | ---: 
createCanvas() | 100,000
setPixel() | 100,000
makeBid() | 150,000
addRewardToPendingWithdrawals() | 100,000
addCommissionToPendingWithdrawals() | --
setMinimumBidAmount() | --
offerCanvasForSaleToAddress() | 100,000
offerCanvasForSale() | 50,000
cancelSellOffer() | 50,000
acceptSellOffer() | 100,000
makeBuyOffer() | 100,000
cancelBuyOffer() | 50,000
acceptBuyOffer() | 100,000
withdraw() | 22677

**Comment by krisu-pl** [comment]
Set gas limit everywhere to 150k for now
